version: '3.7'
services:
  server:
    build: .
    volumes:
      - ${FONT_FOLDER:-/usr/share/fonts}:/usr/share/fonts
    ports:
      - "18412:18412"
      - "7335:7335"
      - "44950:18412" # New versions of Figma also look for this 44950 port
