version: '3.7'
services:
  server:
    build: .
    volumes:
      - ${FONT_FOLDER:-/usr/share/fonts}:/usr/share/fonts
      # Uncomment the lines bellow and adjust them to your need if you need more fonts paths
      # - /home/youruser/anotherfontfolder:/usr/share/fonts/anotherfontfolder
      # - /tmp/yetanotherfontfolder:/usr/share/fonts/yetanotherfontfolder
    ports:
      - "18412:18412"
      - "7335:7335"
      - "44950:18412" # New versions of Figma also look for this 44950 port
